name: Dependency Updates

on:
  schedule:
    # 매주 월요일 오전 9시에 실행
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Update dependencies
        run: |
          npm update
          npm audit fix --force || true
          
      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Run tests after update
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          npm run lint
          npm run type-check
          npm run build
          
      - name: Create Pull Request
        if: steps.verify-changed-files.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'chore: automatic dependency updates'
          body: |
            ## 자동 의존성 업데이트
            
            이 PR은 자동으로 생성된 의존성 업데이트입니다.
            
            ### 변경사항
            - npm 패키지 업데이트
            - 보안 취약점 수정
            
            ### 확인사항
            - [ ] 빌드가 성공적으로 완료됨
            - [ ] 타입 체크 통과
            - [ ] Lint 검사 통과
            
            자동 생성된 PR이므로 배포 전 수동 테스트를 권장합니다.
          branch: chore/dependency-updates
          delete-branch: true